<a href="https://colab.research.google.com/github/AnkitSingh-12/Diamond-Price-Prediction/blob/main/libraries_1numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
l=[1,2,3]
a=np.array(l)
type(a)

numpy.ndarray

In [ ]:

a=np.array([1,2,3])
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
type(a)

numpy.ndarray

In [ ]:
a.ndim

2

**DTYPE**


In [ ]:
#syntax
#    array_varName.dtype
a=np.array([True])
print(a.dtype)
a=np.array([True,10])
print(a.dtype)
a=np.array([True,10,59.7])
print(a.dtype)
a=np.array([True,10,59.7,(10+0j)])
print(a.dtype)
a=np.array([True,10,59.7,'hi'])
print(a.dtype)
a=np.array([True,10,59.7,'hi',{1,2,3}])
print(a.dtype)
a=np.array([True,10,59.7,'hi',{1:3}])
print(a.dtype)
a=np.array([True,10,59.7,'hi',[1,2,3]])#ERROR WE CANT TAKE LIST INSIDE ONE MORE LIST,IF WE CAN TAKE LIST INSIDE ONE MORE LIST ,TUPLE IT WILL CREATE ERROR
print(a.dtype)


#PRIORITY
#bool<int< float<complex<str<object(set,tuple)

bool
int64
float64
complex128
<U32
object
object


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**shape**

In [ ]:
'''
VARIABLE TO GET NUMBER IOF ROWS AND COLUMNS IN ARR
UNIDIMENSIONAL ARRAY---> LENGTH OF THE ARRAY
2D ARRAY -->ROWS and COLUMNS
3D ARRAY -->ROWS,COLUMNS,DEPTH,SLICES
syntax
array_varName.shape
'''

a=np.array([1,2,3])
print(a.shape)
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a.shape)
a=np.array([[1,2],
            [4,5],
            [7,9]])
print(a.shape)

a=np.array([[[1],
            [4]],
            [[7],
             [3]]])
print(a.shape)

(3,)
(3, 3)
(3, 2)
(2, 2, 1)


**RE SHAPE**


In [ ]:
'''
it is used to change the no of col and rows and rows in existing array
syntax
  arr_varname.reshape(rows,col)
'''

a=np.array([[1,2,3,6,],
           [1,2,3,6],
           [1,2,3,6],
           [1,2,3,6]])
print(a.shape)
a=a.reshape(2,8)
print(a.shape)


# note =the product of no of rowa and col should be equals to the no of value present in array

(4, 4)
(2, 8)


In [ ]:
#converting into 2d to 1d

##synatax
#    arr_var_name.reshape(-1)
a=np.array([[1,2,3,6,],
           [1,2,3,6],
           [1,2,3,6],
           [1,2,3,6]])
print(a.shape)
a=a.reshape(-1)
print(a.ndim)

(4, 4)
1


**ndim**

In [ ]:
#synatax
# ndmin=dimension of arary

a=np.array([1,2,3])
print(a.ndim)
a=np.array([1,2,3],ndmin=64)#64 bit is the highest value of the ndmin
print(a.ndim)
a

1
64


array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                                                      2,
                                                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

**arange**

In [ ]:
#syntax
# a=np.arrange(starting value,ending value+-,step value)

a=np.arange(1,10,2)
a
a=np.arange(10,0,-1)
a


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

LINSPACE

In [ ]:
'''SYANTAX
   np.linspace(starting val,ending val,no of value)
   if we are not providig the n0 value by default it will give value'''

a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


**randint**

In [ ]:
'''
unidimensional array

np.random.randint(starting val,ending val+1,no of value)

---> 2d array
np.random.randint(starting val,ending val+1,(rows,col))

--->3d array
np.random.randint(starting val,ending val+1,(slice,rows,col))4


note- ending value exclusive
'''

np.random.randint(1,11,50)
np.random.randint(1,11,(2,3))
np.random.randint(1,11,(2,3,4))

array([[10,  9,  9],
       [ 2,  8,  7]])

**rand**

In [ ]:
'''
syantax

np.random.rand(no of value)
'''

arr=np.random.rand(5)
print(arr)
arr=np.random.rand(2,3)
print(arr)
arr=np.random.rand(2,3,3)
print(arr)

[0.83613364 0.94142328 0.43281632 0.0882091  0.86964831]
[[0.81805287 0.70528371 0.59624917]
 [0.16087394 0.89400913 0.27576103]]
[[[0.42295392 0.69434033 0.99920698]
  [0.4356746  0.13505258 0.51568792]
  [0.35685762 0.46325243 0.7305923 ]]

 [[0.2482963  0.97321634 0.46863372]
  [0.89472681 0.77659246 0.31554355]
  [0.23968176 0.60586847 0.17615583]]]


**randn()**


In [26]:
'''
it is used to generate random no between infinity to infinity
it is present in random module and random module present in numpypackage


syantax
np.random.randn(no of value)
'''
arr=np.random.randn(5)
print(arr)
arr=np.random.randn(2,3)
print(arr)
arr=np.random.randn(2,3,3)
print(arr)



[ 0.45876383 -0.61488515  0.187244   -1.30757935  1.20696023]
[[-0.78417305 -1.53588445 -0.43701779]
 [-0.37874585 -2.34831091  0.75457049]]
[[[ 1.06699747  1.46623749 -1.15353757]
  [ 0.14007    -0.048102    2.39104184]
  [-0.17406079  1.25131495  0.36046749]]

 [[-0.17813177  1.06743722 -1.6606749 ]
  [ 1.89800856 -0.52752966  0.93524982]
  [-1.23016181  1.14221147 -1.30902194]]]


**choice**

In [27]:
'''

synatx
np.random.choice([list of value])
'''
np.random.choice([1,2,'hii',90.8,True])

np.str_('2')

**shuffle**


In [29]:
'''syntax
np.random.shuffl(col/arr_var)'''

arr=np.array([1,2,7.8,'hii',False])

np.random.shuffle(arr)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


**copy**


In [30]:
'''
syantx

new_arr=old_arr.copy()
'''
arr=np.array([1,2,3,4,5])
arr1=arr.copy()
arr[1]=7
print(arr1)
print(arr)

[1 2 3 4 5]
[1 7 3 4 5]


**view**

In [32]:
'''
syantax
new_arr=old_arr.view()
'''
arr=np.array([1,2,3,4,5])
arr1=arr.view()
arr[1]=7
print(arr1)
print(arr)



[1 7 3 4 5]
[1 7 3 4 5]


**zeros**


In [34]:
'''
syantax
#np.zeros(no values)
#np.zeros((rows,col))#2 dimensional array
#np.zeros((slice,rows,col))#3 dimensional array
'''
arr=np.zeros((4,4,10))
print(arr)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


**ones**

In [37]:
'''
synatx

np.ones(values)
np.ones((rows,col))
np.ones((slices,rows,col))

'''
arr=np.ones(10)
print(arr)
arr=np.ones((3,3))
print(arr)
arr=np.ones((2,3,4))
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


**identity**


In [39]:
'''synatx
np.identity(values of matrix)
'''
arr=np.identity(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
